import Head from "next/head";

import { Comic } from "types/types";
import { getComic } from 'dh-marvel/services/marvel/marvel.service';
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";

import { styled } from '@mui/system';
import { Box, Container } from "@mui/material";

interface DataProps {
    data: Comic
}

export const getStaticPaths = async () => {

    return {
        paths: [{ params: { id: '376' } }],
        fallback: true,
    };
};

export const getStaticProps = async ({ params }: any) => {
    const data = await getComic(Number(params.id))

    return {
        props: { data },
        revalidate: 60 * 60
    }
}

const Description = styled(`p`)({
    padding: '1rem',
    textAlign: 'justify',

})

const Price = styled('p')`
    text-align: right;
    margin: 0 auto;
    &.primary{
        color: white;
        font-weight: bolder;
        font-size: x-large;

        :first-child{
            margin: 0.75rem 0;
            text-decoration: underline;
            font-family: Tahoma, Geneva, Verdana, sans-serif;
            letter-spacing: 2px;
            text-align: left;
            text-transform: uppercase;
        }
    }
    
    &.secondary{
        color: lightgray;
        text-decoration: line-through;
    }
`

export default function DatailPage(props: DataProps) {
    const comic = props?.data;
    const oPrice = (comic.oldPrice).toFixed(2);
    const price = (comic.price).toFixed(2);

    console.log(comic);

    if (!comic) {
        return (
            <>
                <Head>
                    <title>DH | Marvel Comics</title>
                    <meta name="description" content="Project generated by create next app for Certified Tech Developer checkpoint." />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <BodySingle>
                    <h3>Loading...</h3>
                </BodySingle>
            </>
        );
    }

    return (
        <>
            <Head>
                <title>{`DH | Marvel Comics - ${comic.title} Detail`}</title>
                <meta name="og:description" content={comic.description} />
                <meta name="og:title" content={comic.title} />
            </Head>
            <BodySingle title={`${comic.title} Detail`}>
                <Box
                    display='flex'
                    justifyContent='center'
                    gap='1.5rem'

                    sx={{
                        flexWrap: { xs: 'wrap', md: 'nowrap' },
                        padding: { lg: '5rem' }
                    }}
                >
                    <picture>
                        <img
                            src={comic.thumbnail.path + "." + comic.thumbnail.extension}
                            alt={comic.title}
                        />
                    </picture>
                    <Box
                        display='flex'
                        justifyContent='center'
                        flexWrap='wrap'
                    >
                        <Description>{comic.description}</Description>
                        <div
                            style={{
                                margin: '1rem',
                                padding: '0.5rem 1.5rem',
                                background: '#1976d2',
                                border: 'solid #1976d2 1px',
                                borderRadius: '.5rem',
                                height: '9rem',
                                width: '14rem',
                            }}

                        >
                            <Price className="primary">Price</Price>
                            <Price className="secondary">${oPrice}</Price>
                            <Price className="primary">${price}</Price>
                        </div>
                    </Box>
                </Box>
            </BodySingle>
        </>
    )
}
